---
- name: Deploy To Tomcat
  hosts: web
  connection: local
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/lib/jenkins/5013/workspace/2023MavenWebAppPipelineWithAnsible/target/2023MavenWebAppPipelineWithAnsible.war"
        dest: "/opt/tomcat/webapps/2023MavenWebAppPipelineWithAnsible.war"
        remote_src: yes

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted

